/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodDeliveryIndexRouteImport } from './routes/food-delivery/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodDeliveryIndexRoute = FoodDeliveryIndexRouteImport.update({
  id: '/food-delivery/',
  path: '/food-delivery/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/food-delivery': typeof FoodDeliveryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/food-delivery': typeof FoodDeliveryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/food-delivery/': typeof FoodDeliveryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/food-delivery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/food-delivery'
  id: '__root__' | '/' | '/food-delivery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodDeliveryIndexRoute: typeof FoodDeliveryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-delivery/': {
      id: '/food-delivery/'
      path: '/food-delivery'
      fullPath: '/food-delivery'
      preLoaderRoute: typeof FoodDeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodDeliveryIndexRoute: FoodDeliveryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
